version: "3.1"

services:
  nginx:
    image: mmeet/nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"

  database:
    image: postgres:14-alpine
    container_name: mmeet_database
    restart: always
    environment:
      POSTGRES_DB: mmeet
      POSTGRES_USER: mmeet
      POSTGRES_PASSWORD: r/y<e-d]sP!,/V<D2KEr<
    ports:
      - "5432:5432"
    volumes:
      - /opt/app/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine
    container_name: mmeet_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass j5fy523U2hbU
    volumes:
      - /opt/app/redis_data:/data
#    environment:
#      - REDIS_PASSWORD=j5fy523U2hbU

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mmeet_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=VxdS23D8h34s
    volumes:
      - /opt/app/rabbitmq_data:/var/lib/rabbitmq

  website:
    image: mmeet/website:latest
    container_name: website
    restart: always
    expose:
      - "3000"

  user-api:
    image: mmeet/user-api:latest
    container_name: user-api
    restart: always
    expose:
      - "3000"
    depends_on:
      - database
      - rabbitmq
      - redis
