export const LOGIN = 'LOGIN';

export const REGISTRATION = 'REGISTRATION';

export const HOME = 'HOME';

export const HOME_WATCH_MMEET_VIDEO = 'HOME_WATCH_MMEET_VIDEO';

export const HOME_PROFILE = 'HOME_PROFILE';
export const HOME_PROFILE_CONTACT_US = 'HOME_PROFILE_CONTACT_US';

export const HOME_PROFILE_INVITE_FRIEND = 'HOME_PROFILE_INVITE_FRIEND';
export const HOME_PROFILE_INVITE_FRIEND_INFO =
    'HOME_PROFILE_INVITE_FRIEND_INFO';
export const HOME_PROFILE_INVITE_FRIEND_STATISTIC =
    'HOME_PROFILE_INVITE_FRIEND_STATISTIC';
export const HOME_PROFILE_INVITE_FRIEND_STATISTIC_INFO =
    'HOME_PROFILE_INVITE_FRIEND_STATISTIC_INFO';
export const HOME_PROFILE_INVITE_FRIEND_QUESTIONS =
    'HOME_PROFILE_INVITE_FRIEND_QUESTIONS';

export const HOME_PROFILE_MY_VIDEOS = 'HOME_PROFILE_MY_VIDEOS';
export const HOME_PROFILE_EDIT_VIDEO_RECORD = 'HOME_PROFILE_EDIT_VIDEO_RECORD';
export const HOME_PROFILE_EDIT_VIDEO_REVIEW = 'HOME_PROFILE_EDIT_VIDEO_REVIEW';
export const HOME_PROFILE_EDIT_VIDEO_WATCH_ANSWER =
    'HOME_PROFILE_EDIT_VIDEO_WATCH_ANSWER';
export const HOME_PROFILE_MY_VIDEOS_INFO = 'HOME_PROFILE_MY_VIDEOS_INFO';

export const HOME_PROFILE_FIND_OPTIONS = 'HOME_PROFILE_FIND_OPTIONS';

export const HOME_MATCHES_SUBSCRIPTIONS = 'HOME_MATCHES_SUBSCRIPTIONS';
export const HOME_MATCHES_SUBSCRIPTIONS_INFO =
    'HOME_MATCHES_SUBSCRIPTIONS_INFO';

export const HOME_MATCHES_DETAILS = 'HOME_MATCHES_DETAILS';
export const HOME_MATCHES_DETAILS_COMPLAINT = 'HOME_MATCHES_DETAILS_COMPLAINT';
export const HOME_MATCHES_PROPOSE_MEETING = 'HOME_MATCHES_PROPOSE_MEETING';
